-- Insert sample locations
INSERT INTO public.locations (city, country, coordinates)
VALUES 
    ('Bali', 'Indonesia', '{"lat": -8.4095, "lng": 115.1889}'::jsonb),
    ('Rishikesh', 'India', '{"lat": 30.0869, "lng": 78.2676}'::jsonb),
    ('Tulum', 'Mexico', '{"lat": 20.2114, "lng": -87.4654}'::jsonb),
    ('Sedona', 'United States', '{"lat": 34.8697, "lng": -111.7607}'::jsonb),
    ('Ubud', 'Indonesia', '{"lat": -8.5069, "lng": 115.2625}'::jsonb)
ON CONFLICT (city, country) DO NOTHING;

-- Insert sample retreat types
INSERT INTO public.retreat_types (name, description, icon)
VALUES 
    ('Meditation', 'Focus on mindfulness and inner peace', '🧘'),
    ('Yoga', 'Traditional yoga practices and philosophy', '🧘‍♀️'),
    ('Wellness', 'Overall health and wellness programs', '💆'),
    ('Spiritual', 'Connect with your spiritual side', '🕊️'),
    ('Mental Health', 'Focus on mental wellbeing', '🧠'),
    ('Detox', 'Cleanse body and mind', '🥗'),
    ('Fitness', 'Physical fitness and training', '💪'),
    ('Silent', 'Practice silence and self-reflection', '🤫'),
    ('Couples', 'Strengthen relationships', '💑'),
    ('Weight Loss', 'Healthy weight management', '⚖️'),
    ('Healing', 'Natural healing and recovery', '🌿'),
    ('Ayurvedic', 'Traditional Ayurvedic practices', '🪷')
ON CONFLICT (name) DO NOTHING;

-- Insert sample retreats
INSERT INTO public.retreats (
    title,
    description,
    location_id,
    price,
    duration,
    start_date,
    end_date,
    type,
    amenities,
    images,
    host_id,
    rating,
    review_count,
    summary,
    features,
    benefits,
    whats_included,
    whats_not_included,
    staff_insights,
    atmosphere,
    skill_level,
    area,
    food,
    age_group,
    room_type
)
SELECT
    retreat_data.title,
    retreat_data.description,
    (SELECT id FROM public.locations WHERE city = retreat_data.city LIMIT 1),
    retreat_data.price::jsonb,
    retreat_data.duration,
    retreat_data.start_date::timestamp with time zone,
    retreat_data.end_date::timestamp with time zone,
    retreat_data.type::text[],
    retreat_data.amenities::text[],
    retreat_data.images::text[],
    '00000000-0000-0000-0000-000000000000'::uuid, -- placeholder host_id
    retreat_data.rating,
    retreat_data.review_count,
    retreat_data.summary,
    retreat_data.features,
    retreat_data.benefits,
    retreat_data.whats_included,
    retreat_data.whats_not_included,
    retreat_data.staff_insights,
    retreat_data.atmosphere::text[],
    retreat_data.skill_level::text[],
    retreat_data.area::text[],
    retreat_data.food::text[],
    retreat_data.age_group::text[],
    retreat_data.room_type::text[]
FROM (
    VALUES
    (
        'Zen Mountain Meditation Retreat',
        'Immerse yourself in the ancient practice of meditation surrounded by the majestic mountains of Sedona. This transformative retreat combines traditional meditation techniques with modern mindfulness practices.',
        'Sedona',
        '{"amount": 2499, "currency": "USD"}',
        7,
        '2024-06-15',
        '2024-06-22',
        ARRAY['Meditation', 'Spiritual'],
        ARRAY['Mountain View', 'Private Pool', 'Spa', 'Yoga Studio', 'Meditation Garden'],
        ARRAY[
            'https://images.unsplash.com/photo-1532798442725-41036acc7489',
            'https://images.unsplash.com/photo-1574785289548-d7c3d01c1c69',
            'https://images.unsplash.com/photo-1617634667039-8e4cb277ab46',
            'https://images.unsplash.com/photo-1604881991720-f91add269bed',
            'https://images.unsplash.com/photo-1615800002234-05c4d488696c',
            'https://images.unsplash.com/photo-1579126038374-6064e9370f0f'
        ],
        4.9,
        124,
        'Find inner peace and clarity in the heart of Sedona''s red rocks. This week-long meditation retreat offers a perfect blend of guided practices, silent reflection, and natural beauty.',
        'Daily meditation sessions\nMindfulness workshops\nBreathing exercises\nScenic hiking\nSound healing\nSpiritual counseling',
        'Develop a strong meditation practice\nReduce stress and anxiety\nImprove mental clarity\nEnhance emotional balance\nDeepen spiritual connection\nLearn mindfulness techniques',
        'All meals and accommodation\nDaily meditation sessions\nMindfulness workshops\nGuided nature walks\nYoga classes\nJournal and meditation materials',
        'Transportation to/from retreat\nPersonal insurance\nMassage services\nPrivate sessions\nSouvenirs\nAlcoholic beverages',
        'Our experienced meditation teachers bring over 20 years of combined experience in various meditation traditions.',
        ARRAY['For Solo Travelers', 'Spiritual Seekers', 'Couples Friendly'],
        ARRAY['Beginner', 'Intermediate'],
        ARRAY['Mountain', 'Close to Nature'],
        ARRAY['Vegetarian', 'Vegan', 'Gluten Free'],
        ARRAY['25-40', '41-60'],
        ARRAY['Private', 'Shared']
    ),
    (
        'Bali Bliss Yoga Retreat',
        'Experience the magic of Bali while deepening your yoga practice in this luxurious beachfront retreat. Combine traditional Balinese healing with modern yoga techniques.',
        'Bali',
        '{"amount": 2899, "currency": "USD"}',
        10,
        '2024-07-01',
        '2024-07-11',
        ARRAY['Yoga', 'Wellness'],
        ARRAY['Ocean View', 'Infinity Pool', 'Spa', 'Yoga Shala', 'Meditation Garden'],
        ARRAY[
            'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf',
            'https://images.unsplash.com/photo-1573126617899-41f1dffb196c',
            'https://images.unsplash.com/photo-1540539234-c14a20fb7c7b',
            'https://images.unsplash.com/photo-1517398823963-c2dc6fc3e837',
            'https://images.unsplash.com/photo-1591228127791-8e2eaef098d3',
            'https://images.unsplash.com/photo-1518609878373-06d740f60d8b'
        ],
        4.8,
        156,
        'Immerse yourself in the spiritual energy of Bali while advancing your yoga practice. This 10-day retreat combines traditional Balinese healing with modern yoga techniques.',
        'Daily yoga sessions\nMeditation practices\nBalinese healing ceremonies\nCultural excursions\nSpa treatments\nNutrition workshops',
        'Deepen your yoga practice\nLearn traditional Balinese healing\nImprove flexibility and strength\nReduce stress\nConnect with like-minded people\nExperience spiritual growth',
        'Luxury accommodation\nAll meals\nYoga classes\nMeditation sessions\nCultural activities\nAirport transfers',
        'International flights\nTravel insurance\nPersonal expenses\nExtra spa treatments\nShopping\nAlcoholic beverages',
        'Our international team of yoga teachers combines traditional Eastern practices with modern teaching methods.',
        ARRAY['For Solo Travelers', 'Women Only', 'Couples Friendly'],
        ARRAY['All Levels', 'Intermediate'],
        ARRAY['Beach', 'Tropical'],
        ARRAY['Vegetarian', 'Vegan', 'Raw'],
        ARRAY['18-24', '25-40'],
        ARRAY['Private', 'Shared']
    ),
    (
        'Tulum Wellness & Detox Retreat',
        'Reset your body and mind in the tropical paradise of Tulum. This comprehensive wellness retreat combines detox programs with holistic healing practices.',
        'Tulum',
        '{"amount": 3299, "currency": "USD"}',
        14,
        '2024-08-01',
        '2024-08-15',
        ARRAY['Detox', 'Wellness', 'Healing'],
        ARRAY['Beach Access', 'Infinity Pool', 'Spa', 'Fitness Center', 'Juice Bar'],
        ARRAY[
            'https://images.unsplash.com/photo-1582653291997-079a1c04e5a1',
            'https://images.unsplash.com/photo-1544161515-4ab6ce6db874',
            'https://images.unsplash.com/photo-1621275471769-e6aa344546d5',
            'https://images.unsplash.com/photo-1507920676663-3b72429774ff',
            'https://images.unsplash.com/photo-1563417079254-a5c8f387f582',
            'https://images.unsplash.com/photo-1584132967334-10e028bd69f7'
        ],
        4.7,
        98,
        'Transform your health with our comprehensive detox program in beautiful Tulum. Combine cleansing practices with luxury beachfront accommodation.',
        'Personalized detox program\nNutritional counseling\nYoga classes\nMeditation sessions\nBeach activities\nCooking workshops',
        'Complete body detoxification\nWeight management\nIncreased energy levels\nImproved digestion\nBetter sleep patterns\nEnhanced mental clarity',
        'Luxury beachfront accommodation\nDetox meals and juices\nWellness workshops\nYoga classes\nMeditation sessions\nAirport transfers',
        'Flights\nTravel insurance\nExtra spa treatments\nPersonal expenses\nExcursions\nAlcoholic beverages',
        'Our wellness team includes certified nutritionists, yoga teachers, and holistic health practitioners.',
        ARRAY['For Solo Travelers', 'Women Only'],
        ARRAY['Beginner', 'Intermediate'],
        ARRAY['Beach', 'Tropical'],
        ARRAY['Vegan', 'Raw', 'Organic'],
        ARRAY['25-40', '41-60'],
        ARRAY['Private']
    ),
    (
        'Rishikesh Spiritual Journey',
        'Embark on a transformative spiritual journey in the yoga capital of the world. Experience authentic yogic living and ancient wisdom teachings.',
        'Rishikesh',
        '{"amount": 1999, "currency": "USD"}',
        21,
        '2024-09-01',
        '2024-09-22',
        ARRAY['Spiritual', 'Yoga', 'Meditation'],
        ARRAY['River View', 'Meditation Hall', 'Yoga Studio', 'Ayurvedic Center'],
        ARRAY[
            'https://images.unsplash.com/photo-1578762560042-46ad127c95ea',
            'https://images.unsplash.com/photo-1601681147113-98bf7c1e4c89',
            'https://images.unsplash.com/photo-1545389336-cf090694435e',
            'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56',
            'https://images.unsplash.com/photo-1620735692151-26a7e0748429',
            'https://images.unsplash.com/photo-1544161515-4ab6ce6db874'
        ],
        4.9,
        187,
        'Immerse yourself in authentic yogic living and ancient wisdom teachings in Rishikesh, the yoga capital of the world.',
        'Traditional yoga classes\nVedic philosophy\nMeditation sessions\nMantra chanting\nSpiritual discourses\nRiver ceremonies',
        'Spiritual awakening\nDeeper understanding of yoga\nInner peace\nMental clarity\nEmotional balance\nLife transformation',
        'Traditional accommodation\nVegetarian meals\nYoga classes\nMeditation sessions\nSpiritual activities\nLocal excursions',
        'Flights\nVisa fees\nTravel insurance\nPersonal expenses\nShopping\nExtra activities',
        'Learn from traditional yoga masters with decades of experience in authentic yogic practices.',
        ARRAY['Spiritual Seekers', 'For Solo Travelers'],
        ARRAY['All Levels'],
        ARRAY['Mountain', 'River'],
        ARRAY['Vegetarian', 'Ayurvedic'],
        ARRAY['25-40', '41-60', '60+'],
        ARRAY['Shared']
    ),
    (
        'Ubud Healing & Wellness Sanctuary',
        'Find healing and renewal in the cultural heart of Bali. This retreat combines traditional Balinese healing with modern wellness practices.',
        'Ubud',
        '{"amount": 2699, "currency": "USD"}',
        12,
        '2024-10-01',
        '2024-10-13',
        ARRAY['Healing', 'Wellness', 'Spiritual'],
        ARRAY['Jungle View', 'Infinity Pool', 'Spa', 'Meditation Pavilion', 'Healing Center'],
        ARRAY[
            'https://images.unsplash.com/photo-1591604466107-ec97de577aff',
            'https://images.unsplash.com/photo-1606402179428-a57976d71fa4',
            'https://images.unsplash.com/photo-1574695853173-89f47d2035a3',
            'https://images.unsplash.com/photo-1584132915807-fd1f5fbc078f',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
            'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57'
        ],
        4.8,
        143,
        'Experience profound healing and transformation in the spiritual heart of Bali. Combine ancient wisdom with modern wellness practices.',
        'Energy healing sessions\nBalinese ceremonies\nYoga classes\nMeditation\nSound healing\nArt therapy',
        'Emotional healing\nPhysical rejuvenation\nSpiritual growth\nStress relief\nInner peace\nLife balance',
        'Luxury villa accommodation\nOrganic meals\nHealing sessions\nYoga classes\nCeremonies\nAirport transfers',
        'Flights\nTravel insurance\nPersonal expenses\nExtra treatments\nShopping\nAlcoholic beverages',
        'Our healing practitioners combine traditional Balinese wisdom with modern therapeutic techniques.',
        ARRAY['For Solo Travelers', 'Women Only'],
        ARRAY['All Levels'],
        ARRAY['Jungle', 'Mountain'],
        ARRAY['Vegetarian', 'Vegan', 'Organic'],
        ARRAY['25-40', '41-60'],
        ARRAY['Private', 'Shared']
    ),
    (
        'Sacred Valley Ayurvedic Retreat',
        'Experience authentic Ayurvedic healing in the mystical Sacred Valley. This retreat offers traditional treatments and practices for complete rejuvenation.',
        'Sedona',
        '{"amount": 3499, "currency": "USD"}',
        14,
        '2024-11-01',
        '2024-11-15',
        ARRAY['Ayurvedic', 'Healing', 'Wellness'],
        ARRAY['Mountain View', 'Ayurvedic Center', 'Herb Garden', 'Meditation Hall', 'Treatment Rooms'],
        ARRAY[
            'https://images.unsplash.com/photo-1600585154526-990dced4db0d',
            'https://images.unsplash.com/photo-1544161515-4ab6ce6db874',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
            'https://images.unsplash.com/photo-1540539234-c14a20fb7c7b',
            'https://images.unsplash.com/photo-1517398823963-c2dc6fc3e837',
            'https://images.unsplash.com/photo-1591228127791-8e2eaef098d3'
        ],
        4.9,
        167,
        'Immerse yourself in authentic Ayurvedic healing practices surrounded by the sacred mountains. Experience traditional treatments and ancient wisdom.',
        'Ayurvedic consultations\nDaily treatments\nYoga classes\nMeditation sessions\nHerbal medicine workshops\nCooking classes',
        'Complete body rejuvenation\nImproved digestion\nBetter sleep quality\nStress reduction\nEmotional balance\nEnhanced vitality',
        'Luxury accommodation\nAyurvedic meals\nDaily treatments\nYoga classes\nMeditation sessions\nHerbal medicines',
        'Flights\nTravel insurance\nPersonal expenses\nExtra treatments\nShopping\nNon-Ayurvedic meals',
        'Our Ayurvedic doctors bring decades of experience from Kerala, India.',
        ARRAY['Health Enthusiasts', 'Spiritual Seekers'],
        ARRAY['All Levels'],
        ARRAY['Mountain', 'Valley'],
        ARRAY['Ayurvedic', 'Vegetarian'],
        ARRAY['25-40', '41-60'],
        ARRAY['Private']
    ),
    (
        'Mindful Living Retreat',
        'Discover the art of mindful living in a serene mountain setting. Learn practical techniques for bringing mindfulness into everyday life.',
        'Sedona',
        '{"amount": 1999, "currency": "USD"}',
        7,
        '2024-12-01',
        '2024-12-08',
        ARRAY['Meditation', 'Mental Health', 'Wellness'],
        ARRAY['Mountain View', 'Meditation Garden', 'Zen Garden', 'Library', 'Quiet Spaces'],
        ARRAY[
            'https://images.unsplash.com/photo-1518609878373-06d740f60d8b',
            'https://images.unsplash.com/photo-1506126613408-eca07ce68773',
            'https://images.unsplash.com/photo-1552693673-1bf958298935',
            'https://images.unsplash.com/photo-1591604466107-ec97de577aff',
            'https://images.unsplash.com/photo-1606402179428-a57976d71fa4',
            'https://images.unsplash.com/photo-1574695853173-89f47d2035a3'
        ],
        4.7,
        92,
        'Learn practical mindfulness techniques for everyday life in a peaceful mountain setting. Perfect for those seeking mental clarity and emotional balance.',
        'Mindfulness workshops\nGuided meditations\nNature walks\nJournaling sessions\nBreathing exercises\nStress management',
        'Reduced anxiety\nBetter focus\nEmotional resilience\nImproved relationships\nStress management skills\nMindful living practices',
        'Comfortable accommodation\nHealthy meals\nWorkshops\nMeditation sessions\nJournal materials\nGuided activities',
        'Transportation\nTravel insurance\nPersonal expenses\nPrivate sessions\nExtra activities\nMassages',
        'Our mindfulness instructors are certified in MBSR and other evidence-based practices.',
        ARRAY['Beginners', 'Stress Relief Seekers'],
        ARRAY['Beginner', 'Intermediate'],
        ARRAY['Mountain', 'Forest'],
        ARRAY['Vegetarian', 'Vegan'],
        ARRAY['25-40', '41-60'],
        ARRAY['Private', 'Shared']
    ),
    (
        'Tropical Fitness Retreat',
        'Transform your body and mind in tropical paradise. This high-energy retreat combines fitness training with wellness practices.',
        'Bali',
        '{"amount": 2799, "currency": "USD"}',
        10,
        '2024-07-15',
        '2024-07-25',
        ARRAY['Fitness', 'Wellness', 'Weight Loss'],
        ARRAY['Beach Access', 'Fitness Center', 'Pool', 'Spa', 'Training Areas'],
        ARRAY[
            'https://images.unsplash.com/photo-1518611012118-696072aa579a',
            'https://images.unsplash.com/photo-1574680096145-d05b474e2155',
            'https://images.unsplash.com/photo-1579126038374-6064e9370f0f',
            'https://images.unsplash.com/photo-1591604466107-ec97de577aff',
            'https://images.unsplash.com/photo-1606402179428-a57976d71fa4',
            'https://images.unsplash.com/photo-1574695853173-89f47d2035a3'
        ],
        4.8,
        134,
        'Get fit and energized in tropical paradise. This retreat combines intensive fitness training with relaxation and wellness practices.',
        'Daily fitness classes\nNutrition coaching\nBeach workouts\nYoga sessions\nMeditation\nWellness workshops',
        'Improved fitness level\nWeight management\nIncreased energy\nBetter nutrition habits\nMental clarity\nStress reduction',
        'Luxury accommodation\nHealthy meals\nFitness classes\nPersonal training\nNutrition plan\nWellness activities',
        'Flights\nTravel insurance\nPersonal expenses\nExtra massages\nPrivate training\nAlcoholic beverages',
        'Our fitness experts combine modern training methods with holistic wellness practices.',
        ARRAY['Fitness Enthusiasts', 'Weight Loss Goals'],
        ARRAY['All Levels'],
        ARRAY['Beach', 'Tropical'],
        ARRAY['Clean Eating', 'High Protein'],
        ARRAY['25-40', '41-60'],
        ARRAY['Private', 'Shared']
    ),
    (
        'Silent Meditation Intensive',
        'Experience profound inner silence and self-discovery through this intensive silent retreat in the mountains.',
        'Sedona',
        '{"amount": 1799, "currency": "USD"}',
        10,
        '2024-08-15',
        '2024-08-25',
        ARRAY['Silent', 'Meditation', 'Spiritual'],
        ARRAY['Mountain View', 'Meditation Hall', 'Walking Paths', 'Private Rooms'],
        ARRAY[
            'https://images.unsplash.com/photo-1506126613408-eca07ce68773',
            'https://images.unsplash.com/photo-1552693673-1bf958298935',
            'https://images.unsplash.com/photo-1591604466107-ec97de577aff',
            'https://images.unsplash.com/photo-1606402179428-a57976d71fa4',
            'https://images.unsplash.com/photo-1574695853173-89f47d2035a3',
            'https://images.unsplash.com/photo-1584132915807-fd1f5fbc078f'
        ],
        4.9,
        156,
        'Dive deep into silence and self-discovery. This intensive retreat offers a rare opportunity for profound inner exploration and spiritual growth.',
        'Silent meditation\nMindful walking\nContemplative practices\nSpiritual guidance\nQigong\nNature communion',
        'Deep inner peace\nMental clarity\nSpiritual insight\nEmotional healing\nSelf-discovery\nEnhanced awareness',
        'Private accommodation\nVegetarian meals\nMeditation guidance\nSpiritual talks\nMindful walking\nJournal materials',
        'Transportation\nTravel insurance\nPersonal items\nExtra guidance\nBooks\nOutside communication',
        'Our teachers have decades of experience in various meditation traditions.',
        ARRAY['Spiritual Seekers', 'Experienced Meditators'],
        ARRAY['Intermediate', 'Advanced'],
        ARRAY['Mountain', 'Forest'],
        ARRAY['Vegetarian', 'Vegan'],
        ARRAY['25-40', '41-60', '60+'],
        ARRAY['Private']
    ),
    (
        'Couples Healing Journey',
        'Strengthen your relationship through this intimate couples retreat combining therapy, meditation, and sacred practices.',
        'Tulum',
        '{"amount": 3999, "currency": "USD"}',
        7,
        '2024-09-15',
        '2024-09-22',
        ARRAY['Couples', 'Healing', 'Spiritual'],
        ARRAY['Beach Access', 'Private Villas', 'Couples Spa', 'Meditation Space'],
        ARRAY[
            'https://images.unsplash.com/photo-1578762560042-46ad127c95ea',
            'https://images.unsplash.com/photo-1601681147113-98bf7c1e4c89',
            'https://images.unsplash.com/photo-1545389336-cf090694435e',
            'https://images.unsplash.com/photo-1600093463592-8e36ae95ef56',
            'https://images.unsplash.com/photo-1620735692151-26a7e0748429',
            'https://images.unsplash.com/photo-1544161515-4ab6ce6db874'
        ],
        4.8,
        89,
        'Deepen your connection and heal together in paradise. This intimate retreat offers couples therapy, sacred practices, and romantic experiences.',
        'Couples therapy\nTantra workshops\nMeditation sessions\nMassage lessons\nIntimacy practices\nRomantic activities',
        'Stronger relationship\nDeeper connection\nImproved communication\nEmotional healing\nEnhanced intimacy\nShared growth',
        'Luxury villa\nGourmet meals\nTherapy sessions\nCouples activities\nSpa treatments\nPrivate beach time',
        'Flights\nTravel insurance\nPersonal expenses\nExtra activities\nShopping\nAlcoholic beverages',
        'Our relationship experts combine modern therapy with ancient wisdom traditions.',
        ARRAY['Couples Only'],
        ARRAY['All Levels'],
        ARRAY['Beach', 'Tropical'],
        ARRAY['Gourmet', 'Organic'],
        ARRAY['25-40', '41-60'],
        ARRAY['Private']
    ),
    (
        'Weight Loss & Wellness Transformation',
        'Achieve your weight loss goals through a holistic approach combining fitness, nutrition, and mindset coaching.',
        'Tulum',
        '{"amount": 3299, "currency": "USD"}',
        14,
        '2024-10-01',
        '2024-10-15',
        ARRAY['Weight Loss', 'Fitness', 'Wellness'],
        ARRAY['Beach Access', 'Fitness Center', 'Pool', 'Nutrition Lab', 'Spa'],
        ARRAY[
            'https://images.unsplash.com/photo-1518611012118-696072aa579a',
            'https://images.unsplash.com/photo-1574680096145-d05b474e2155',
            'https://images.unsplash.com/photo-1579126038374-6064e9370f0f',
            'https://images.unsplash.com/photo-1591604466107-ec97de577aff',
            'https://images.unsplash.com/photo-1606402179428-a57976d71fa4',
            'https://images.unsplash.com/photo-1574695853173-89f47d2035a3'
        ],
        4.7,
        112,
        'Transform your body and mind through our comprehensive weight loss program. Combine fitness training with nutrition education and mindset coaching.',
        'Personal training\nNutrition workshops\nMindset coaching\nCooking classes\nGroup fitness\nStress management',
        'Sustainable weight loss\nImproved fitness\nHealthy eating habits\nIncreased energy\nBetter self-image\nLifestyle transformation',
        'Luxury accommodation\nCustomized meal plan\nFitness classes\nNutrition coaching\nWellness activities\nTake-home program',
        'Flights\nTravel insurance\nPersonal expenses\nExtra treatments\nPrivate coaching\nAlcoholic beverages',
        'Our weight loss experts use evidence-based methods combined with holistic wellness practices.',
        ARRAY['Weight Loss Goals', 'Fitness Enthusiasts'],
        ARRAY['All Levels'],
        ARRAY['Beach', 'Tropical'],
        ARRAY['Clean Eating', 'Portion Control'],
        ARRAY['25-40', '41-60'],
        ARRAY['Private', 'Shared']
    ),
    (
        'Digital Detox & Nature Immersion',
        'Disconnect from technology and reconnect with nature in this transformative retreat in the mountains.',
        'Sedona',
        '{"amount": 2199, "currency": "USD"}',
        7,
        '2024-11-15',
        '2024-11-22',
        ARRAY['Mental Health', 'Wellness', 'Spiritual'],
        ARRAY['Mountain View', 'Hiking Trails', 'Meditation Spaces', 'Art Studio'],
        ARRAY[
            'https://images.unsplash.com/photo-1506126613408-eca07ce68773',
            'https://images.unsplash.com/photo-1552693673-1bf958298935',
            'https://images.unsplash.com/photo-1591604466107-ec97de577aff',
            'https://images.unsplash.com/photo-1606402179428-a57976d71fa4',
            'https://images.unsplash.com/photo-1574695853173-89f47d2035a3',
            'https://images.unsplash.com/photo-1584132915807-fd1f5fbc078f'
        ],
        4.8,
        78,
        'Break free from digital addiction and rediscover your connection with nature. This retreat offers a perfect balance of guided activities and personal exploration.',
        'Nature walks\nArt therapy\nMindfulness practices\nGroup discussions\nJournaling\nOutdoor meditation',
        'Digital-life balance\nMental clarity\nNature connection\nStress reduction\nCreative expression\nImproved sleep',
        'Cozy accommodation\nOrganic meals\nGuided activities\nArt supplies\nJournal materials\nWellness workshops',
        'Transportation\nTravel insurance\nPersonal items\nExtra activities\nDevices storage\nOutside communication',
        'Our facilitators are experts in nature therapy and mindfulness practices.',
        ARRAY['Digital Detox', 'Nature Lovers'],
        ARRAY['All Levels'],
        ARRAY['Mountain', 'Forest'],
        ARRAY['Organic', 'Farm to Table'],
        ARRAY['25-40', '41-60'],
        ARRAY['Private', 'Shared']
    ),
    (
        'Sacred Feminine Healing Retreat',
        'Embrace your divine feminine energy in this women-only retreat combining ancient wisdom with modern healing practices.',
        'Ubud',
        '{"amount": 2599, "currency": "USD"}',
        10,
        '2024-12-05',
        '2024-12-15',
        ARRAY['Healing', 'Spiritual', 'Wellness'],
        ARRAY['Jungle View', 'Sacred Temple', 'Spa', 'Women''s Circle Space'],
        ARRAY[
            'https://images.unsplash.com/photo-1591604466107-ec97de577aff',
            'https://images.unsplash.com/photo-1606402179428-a57976d71fa4',
            'https://images.unsplash.com/photo-1574695853173-89f47d2035a3',
            'https://images.unsplash.com/photo-1584132915807-fd1f5fbc078f',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
            'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57'
        ],
        4.9,
        145,
        'Connect with your divine feminine essence in the magical setting of Ubud. This women-only retreat offers sacred ceremonies, healing practices, and sisterhood.',
        'Women''s circles\nSacred ceremonies\nYoga classes\nDance therapy\nEnergy healing\nMoon rituals',
        'Feminine empowerment\nEmotional healing\nSelf-love\nIntuitive development\nSisterhood bonds\nSpiritual connection',
        'Luxury villa accommodation\nOrganic meals\nCeremonies\nHealing sessions\nSacred activities\nRitual materials',
        'Flights\nTravel insurance\nPersonal expenses\nExtra treatments\nShopping\nAlcoholic beverages',
        'Our facilitators are experienced in women''s empowerment and sacred feminine practices.',
        ARRAY['Women Only', 'Spiritual Seekers'],
        ARRAY['All Levels'],
        ARRAY['Jungle', 'Sacred Sites'],
        ARRAY['Vegetarian', 'Vegan'],
        ARRAY['25-40', '41-60'],
        ARRAY['Private', 'Shared']
    ),
    (
        'Eco-Conscious Yoga Adventure',
        'Combine yoga practice with environmental consciousness in this unique eco-retreat experience.',
        'Tulum',
        '{"amount": 2399, "currency": "USD"}',
        8,
        '2024-12-10',
        '2024-12-18',
        ARRAY['Yoga', 'Wellness', 'Spiritual'],
        ARRAY['Eco Lodges', 'Sustainable Garden', 'Beach Access', 'Yoga Shala'],
        ARRAY[
            'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf',
            'https://images.unsplash.com/photo-1573126617899-41f1dffb196c',
            'https://images.unsplash.com/photo-1540539234-c14a20fb7c7b',
            'https://images.unsplash.com/photo-1517398823963-c2dc6fc3e837',
            'https://images.unsplash.com/photo-1591228127791-8e2eaef098d3',
            'https://images.unsplash.com/photo-1518609878373-06d740f60d8b'
        ],
        4.7,
        98,
        'Experience yoga in harmony with nature at our eco-conscious retreat. Learn sustainable living practices while deepening your yoga practice.',
        'Eco-yoga sessions\nSustainability workshops\nOrganic gardening\nBeach cleanups\nMeditation\nGreen living talks',
        'Deeper yoga practice\nEnvironmental awareness\nSustainable living skills\nMindful consumption\nNature connection\nCommunity building',
        'Eco-lodge stay\nOrganic meals\nYoga classes\nWorkshops\nBeach activities\nGarden activities',
        'Flights\nTravel insurance\nPersonal items\nExtra activities\nShopping\nNon-eco products',
        'Our teachers are certified in yoga and passionate about environmental conservation.',
        ARRAY['Eco-Conscious', 'Yoga Enthusiasts'],
        ARRAY['All Levels'],
        ARRAY['Beach', 'Eco Resort'],
        ARRAY['Organic', 'Plant Based'],
        ARRAY['25-40', '41-60'],
        ARRAY['Shared']
    ),
    (
        'Holistic Healing Immersion',
        'Experience a variety of healing modalities in this comprehensive wellness retreat.',
        'Ubud',
        '{"amount": 3099, "currency": "USD"}',
        14,
        '2024-12-15',
        '2024-12-29',
        ARRAY['Healing', 'Wellness', 'Spiritual'],
        ARRAY['Healing Center', 'Meditation Space', 'Spa', 'Sacred Garden'],
        ARRAY[
            'https://images.unsplash.com/photo-1600585154526-990dced4db0d',
            'https://images.unsplash.com/photo-1544161515-4ab6ce6db874',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
            'https://images.unsplash.com/photo-1540539234-c14a20fb7c7b',
            'https://images.unsplash.com/photo-1517398823963-c2dc6fc3e837',
            'https://images.unsplash.com/photo-1591228127791-8e2eaef098d3'
        ],
        4.8,
        167,
        'Immerse yourself in various healing modalities from around the world. This comprehensive retreat offers both traditional and modern healing practices.',
        'Energy healing\nSound therapy\nAcupuncture\nHerbal medicine\nReiki sessions\nBreathwork',
        'Physical healing\nEmotional balance\nEnergetic cleansing\nSpiritual growth\nHolistic health\nSelf-healing tools',
        'Luxury accommodation\nOrganic meals\nHealing sessions\nWorkshops\nHerbal remedies\nWellness activities',
        'Flights\nTravel insurance\nPersonal expenses\nExtra treatments\nShopping\nOutside medications',
        'Our international healing practitioners bring expertise from various traditions.',
        ARRAY['Healing Seekers', 'Spiritual Enthusiasts'],
        ARRAY['All Levels'],
        ARRAY['Jungle', 'Sacred Sites'],
        ARRAY['Healing Foods', 'Organic'],
        ARRAY['25-40', '41-60', '60+'],
        ARRAY['Private', 'Shared']
    )
) AS retreat_data (
    title, description, city, price, duration, start_date, end_date, type, amenities, 
    images, rating, review_count, summary, features, benefits, whats_included, 
    whats_not_included, staff_insights, atmosphere, skill_level, area, food, 
    age_group, room_type
); 